# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sirena.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csirena.proto\x12\x0esirena_service\"\x17\n\x07\x43hannel\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"9\n\x05\x45vent\x12\x10\n\x08priority\x18\x01 \x01(\r\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05\x61udio\x18\x03 \x01(\x0c\x32Q\n\rSirenaService\x12@\n\nSendEvents\x12\x17.sirena_service.Channel\x1a\x15.sirena_service.Event\"\x00\x30\x01\x42\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sirena_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto'
  _globals['_CHANNEL']._serialized_start=32
  _globals['_CHANNEL']._serialized_end=55
  _globals['_EVENT']._serialized_start=57
  _globals['_EVENT']._serialized_end=114
  _globals['_SIRENASERVICE']._serialized_start=116
  _globals['_SIRENASERVICE']._serialized_end=197
# @@protoc_insertion_point(module_scope)
