# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sirena.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sirena.proto',
  package='sirena_service',
  syntax='proto3',
  serialized_options=b'Z\007./proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0csirena.proto\x12\x0esirena_service\"\x16\n\x06\x43hanel\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"\x19\n\x05\x45vent\x12\x10\n\x08priority\x18\x01 \x01(\r2P\n\rSirenaService\x12?\n\nSendEvents\x12\x16.sirena_service.Chanel\x1a\x15.sirena_service.Event\"\x00\x30\x01\x42\tZ\x07./protob\x06proto3'
)




_CHANEL = _descriptor.Descriptor(
  name='Chanel',
  full_name='sirena_service.Chanel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='sirena_service.Chanel.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=54,
)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='sirena_service.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='priority', full_name='sirena_service.Event.priority', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['Chanel'] = _CHANEL
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Chanel = _reflection.GeneratedProtocolMessageType('Chanel', (_message.Message,), {
  'DESCRIPTOR' : _CHANEL,
  '__module__' : 'sirena_pb2'
  # @@protoc_insertion_point(class_scope:sirena_service.Chanel)
  })
_sym_db.RegisterMessage(Chanel)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'sirena_pb2'
  # @@protoc_insertion_point(class_scope:sirena_service.Event)
  })
_sym_db.RegisterMessage(Event)


DESCRIPTOR._options = None

_SIRENASERVICE = _descriptor.ServiceDescriptor(
  name='SirenaService',
  full_name='sirena_service.SirenaService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=83,
  serialized_end=163,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendEvents',
    full_name='sirena_service.SirenaService.SendEvents',
    index=0,
    containing_service=None,
    input_type=_CHANEL,
    output_type=_EVENT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIRENASERVICE)

DESCRIPTOR.services_by_name['SirenaService'] = _SIRENASERVICE

# @@protoc_insertion_point(module_scope)
