# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sirena_pb2 as sirena__pb2


class SirenaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendEvents = channel.unary_stream(
                '/sirena_service.SirenaService/SendEvents',
                request_serializer=sirena__pb2.Chanel.SerializeToString,
                response_deserializer=sirena__pb2.Event.FromString,
                )


class SirenaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SirenaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SendEvents,
                    request_deserializer=sirena__pb2.Chanel.FromString,
                    response_serializer=sirena__pb2.Event.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sirena_service.SirenaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SirenaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/sirena_service.SirenaService/SendEvents',
            sirena__pb2.Chanel.SerializeToString,
            sirena__pb2.Event.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
